version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.2-bullseye
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
